name: Update Sourcemod

on:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest 
    steps:
    
      - name: check version of linux Sourcemod
        run: |
          latest_remote=$(curl -sL https://sm.alliedmods.net/smdrop/1.11/sourcemod-latest-linux )
          local_version=$(curl -sL https://raw.githubusercontent.com/TMG-CSGO/SM/main/sourcemod-latest-linux )
       
          if [[ "$latest_remote" != "$local_version" ]]; then
                echo "New version detected, updating Sourcemod..."
          else        
                echo "Latest version already installed."
                exit 1
          fi
          
          if [ $? -ne 0 ]; then
                echo "Error fetching versions, exiting."
                exit 1    
          fi
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Sourcemod
        run: |
          curl -L "https://www.sourcemod.net/latest.php?os=linux&version=1.11" -o sourcemod.tar.gz
          tar -xzf sourcemod.tar.gz
          rm -rf cfg
          rm -rf addons/sourcemod/scripting

      - name: Upload Sourcemod
        uses: actions/upload-artifact@v3
        with:
          name: sourcemod
          path: |
            addons/sourcemod/configs/geoip/*
            addons/sourcemod/configs/sql-init-scripts/*
            addons/sourcemod/bin/*
            addons/sourcemod/extensions/*
            addons/sourcemod/gamedata/*
            addons/sourcemod/translations/*.txt

      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          repository: TMG-CSGO/SM
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sourcemod
          path: addons/sourcemod/

      - name: Commit Files
        run: |
          rm -rf sourcemod-latest-linux
          wget https://sm.alliedmods.net/smdrop/1.11/sourcemod-latest-linux
          git config --local core.autocrlf false
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Sourcemod Auto Updater"
          git push
