name: Download latest SourceMod and upload

on:
  push:
  
jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: 'TMG-CSGO/SM'  # Repository to upload to
          ref: 'main'

      - name: Download latest SourceMod release
        run: |

          URL="https://www.sourcemod.net/latest.php?os=unix&version=1.11"
          curl -L $URL -o sourcemod.tar.gz
          mkdir sourcemod
          tar -xzf sourcemod.tar.gz -C sourcemod --strip-components 1

      - name: Upload to repo
        run: |
          cp -r sourcemod/* .
          git config user.name "alix1383"
          git config user.email "hajali1383@gmail.com"
          git add .
          git commit -m "Upload SourceMod $VERSION"
          git push
