name: Download and Upload Sourcemod
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Sourcemod
      run: |
        curl -LJO https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6934-linux.tar.gz
        tar -xzf sourcemod-1.11.0-git6934-linux.tar.gz

    - name: Upload Sourcemod
      uses: actions/upload-artifact@v2
      with:
        name: sourcemod
        path: addons/sourcemod

    - name: Clone Repo
      uses: actions/checkout@v2
      with:
        repository: TMG-CSGO/SM
        ref: main
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: sourcemod

    - name: Commit Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add addons/sourcemod
        git commit -m "Updated Sourcemod"
        git push
