name: Update Sourcemod

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Sourcemod
        run: |
          curl -L "https://www.sourcemod.net/latest.php?os=linux&version=1.11" -o sourcemod.tar.gz
          tar -xzf sourcemod.tar.gz
          rm -rf cfg
          rm -rf addons/sourcemod/scripting

      - name: Upload Sourcemod
        uses: actions/upload-artifact@v3
        with:
          name: sourcemod
          path: |
            addons/sourcemod/configs/geoip/*
            addons/sourcemod/configs/sql-init-scripts/*
            addons/sourcemod/bin/*
            addons/sourcemod/extensions/*
            addons/sourcemod/gamedata/*
            addons/sourcemod/translations/*.txt

      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          repository: TMG-CSGO/SM
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: sourcemod
          path: addons/sourcemod/

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m "Sourcemod Auto Updater"
          git push
