name: 🚀 Deploy SV_main

on:
  push:

jobs:
  web-deploy:
    name: 🎉 Deploy SV_main 
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.SFTP_HOST_SV_main }}
          username: ${{ secrets.SFTP_USERNAME_SV_main }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.PORT }}
          server-dir: /home/gr/masteraddons/SM/