name: Update Sourcemod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check version of linux Sourcemod
        run: |
                remote=$( curl -sL  https://sm.alliedmods.net/smdrop/1.11/sourcemod-latest-linux )
                local=$( curl -sL  https://raw.githubusercontent.com/TMG-CSGO/SM/main/sourcemod-latest-linux )
    
                if [ "$remote" != "$local" ]; then
                        echo "{run_jobs}={true}" > $GITHUB_STATE
                else        
                        echo "{run_jobs}={false}" > $GITHUB_STATE
                fi
