name: Update Sourcemod

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest 
    steps:
    
      - name: check version of linux Sourcemod
        run: |
          latest_remote=$(curl -L https://sm.alliedmods.net/smdrop/1.11/sourcemod-latest-linux )
          local_version=$(curl -L https://raw.githubusercontent.com/TMG-CSGO/SM/main/sourcemod-latest-linux )
          
          echo "AND"
          echo $latest_remote
          echo $local_version
          echo "AND"
          
          if [[ "$latest_remote" != "$local_version" ]]; then
                echo "New version detected, updating Sourcemod..."
          else        
                echo "Latest version already installed."
                exit 1 
          fi
          
          if [ $? -ne 0 ]; then
                echo "Error fetching versions, exiting."
                exit 1    
          fi
