name: Update Sourcemod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        - name: Download data
          run: |
              data=$(curl -sL https://sm.alliedmods.net/smdrop/1.11/sourcemod-latest-linux )
              "MY_DATA=${data}" >> $GITHUB_ENV
               echo ${{ env.MY_DATA }}


